# Server configuration
server:
  port: 8082

spring:
  application:
    name: kafka-consumer-wikimedia

  datasource:
    url: jdbc:mysql://localhost:3306/kafkadb
    username: root
    password: rootuser

  jpa:
    open-in-view: false
    ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

  kafka:
    consumer:
      # The address of the Kafka broker(s) for the consumer
      bootstrap-servers: localhost:9092

      # The consumer group ID to which this application belongs
      group-id: myGroup

      # Set the starting offset for new consumers (earliest: start from beginning of topic)
      auto-offset-reset: earliest

      # Deserializer for the consumer key (interprets the key data as a String)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # Deserializer for the consumer value (interprets the value data as a String)
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"
